---
- name: Install dependencies
  apt:
    name:
      - curl
      - gnupg
      - apt-transport-https
    state: present
    update_cache: yes

- name: Add Vector repository key
  apt_key:
    url: https://packages.timber.io/vector/gpg.asc
    state: present

- name: Add Vector repository
  apt_repository:
    repo: "deb [arch=amd64] https://packages.timber.io/vector/{{ vector_version }}/{{ ansible_distribution | lower }} {{ ansible_distribution_release | lower }} main"
    state: present
    filename: vector

- name: Install Vector
  apt:
    name: vector
    state: present
    update_cache: yes

- name: Configure Vector
  template:
    src: vector.yml.j2
    dest: /etc/vector/vector.yml
    owner: root
    group: root
    mode: '0644'

- name: Ensure Vector service is enabled and started
  systemd:
    name: vector
    state: started
    enabled: yes
    daemon_reload: yes
